onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - unrs-resolver

# Note: Align with Renovate settings (`config:best-practices` > `security:minimumReleaseAgeNpm`)
minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  # Renovate security update: vite@8.0.5
  - vite@8.0.5
