on:
  push:
    branches:
      - main

name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Apps token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
      - uses: google-github-actions/release-please-action@v3
        with:
          token: ${{ steps.generate_token.outputs.token }}
          release-type: node
          package-name: hama-color
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true
